# Generated by Django 3.2.13 on 2022-06-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alarm',
            fields=[
                ('pkey', models.IntegerField(primary_key=True, serialize=False)),
                ('atime', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='intruder',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('intr_time', models.TextField(null=True)),
                ('intr_date', models.TextField(null=True)),
                ('picture', models.ImageField(null=True, upload_to='pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='intruder_stat',
            fields=[
                ('pkey', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('intr_state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='owner',
            fields=[
                ('name', models.TextField(max_length=100, primary_key=True, serialize=False)),
                ('own_picture', models.ImageField(null=True, upload_to='pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='toggle',
            fields=[
                ('pkey', models.IntegerField(primary_key=True, serialize=False)),
                ('intrudersys', models.BooleanField(default=False)),
                ('led', models.BooleanField(default=False)),
                ('stream', models.BooleanField(default=False)),
            ],
        ),
    ]
